### ISSUE TITLE
eachDecl has been deprecated

### ISSUE THREAD

**Issue by passcod** [iAdramelk/postcss-urlrewrite#2]
When running, this message appears:

    Container#eachDecl is deprecated. Use Container#walkDecls instead.

**Comment by iAdramelk** [comment]
Hi! didn't thought that somebody still using this. :) Will try to update this weekend.

**Comment by passcod** [comment]
Thanks :) And yeah, after evaluating a bunch of other modules, yours was the best for the job.

**Comment by iAdramelk** [comment]
Updated dependencies and published version `0.2.0`. Should work without errors now.

**Comment by passcod** [comment]
Awesome, thanks :)
