### ISSUE TITLE
Deprecation warning regarding 'util.isArray' with the latest node.js release.

### ISSUE THREAD

**Issue by aKandzior** [iAdramelk/postcss-urlrewrite#5]
In lines 16 and 20 of  [lib/urlrewrite.js](https://github.com/iAdramelk/postcss-urlrewrite/blob/master/lib/urlrewrite.js) `util.isArray` is used.

This generates a deprecation warning with the latest `node.js` release.

See https://nodejs.org/api/deprecations.html#DEP0044.

The lines in question should be replaced by `Array.isArray`.

**Comment by iAdramelk** [comment]
Thanks! Updated and published 0.3.0.
